#ifndef _GPS_READER_MSGIDS_H_
#define _GPS_READER_MSGIDS_H_

#define GPS_READER_GPS_INFO_MSG  (0x1901)
#define GPS_READER_GPS_GPGGA_MSG (0x1902)
#define GPS_READER_GPS_GPGSA_MSG (0x1903)
#define GPS_READER_GPS_GPRMC_MSG (0x1904)
#define GPS_READER_GPS_GPVTG_MSG (0x1905)

#endif // _GPS_READER_MSGIDS_H_